#!/usr/bin/env bash
function sshrc() {
    local SSHHOME=${SSHHOME:=~}
    if [ -f $SSHHOME/.sshrc ]; then
        local files=.sshrc
        if [ -d $SSHHOME/.sshrc.d ]; then
            files="$files .sshrc.d"
        fi
        ssh -t "$@" "
            if [ -e /etc/motd ];then cat /etc/motd; fi
            if [ \"\$(base64 --help | grep -e '-D')\" != \"\" ];then echo '-Di' > /tmp/b64decode; else echo '-di' > /tmp/b64decode; fi
            export SSHHOME=\$(mktemp -d -t .$(whoami).sshrc.XXXX)
            echo $'"$(cat `which sshrc` | base64)"' | base64 \$(cat /tmp/b64decode) > \$SSHHOME/sshrc
            chmod +x \$SSHHOME/sshrc
            echo $'"$( cat << 'EOF' | base64
#!/usr/bin/env bash
bash --rcfile <(echo '
if [ -e /etc/bash.bashrc ]; then source /etc/bash.bashrc; fi
if [ -e ~/.bashrc ]; then source ~/.bashrc; fi
source '$SSHHOME'/.sshrc;
export PATH=$PATH:'$SSHHOME'
')
EOF
)"' | base64 \$(cat /tmp/b64decode) > \$SSHHOME/bashsshrc
            chmod +x \$SSHHOME/bashsshrc
            export SSHRCCLEANUP=\$SSHHOME
            echo $'"$(tar cz -h -C $SSHHOME $files | base64)"' | base64 \$(cat /tmp/b64decode) | tar mxz -C \$SSHHOME
            export SSHHOME=\$SSHHOME
            \$SSHHOME/bashsshrc
            rm -rf \$SSHRCCLEANUP
            "
    else
        echo "No such file: $SSHHOME/.sshrc"
    fi
}
if [ $1 ]; then
    sshrc $@
else
    ssh
fi
