#!/usr/bin/env bash
function sshrc() {
    local SSHHOME=${SSHHOME:=~}
    if [ -f $SSHHOME/.sshrc ]; then
        local files=.sshrc
        if [ -d $SSHHOME/.sshrc.d ]; then
            files="$files .sshrc.d"
        fi
        SIZE=$(tar cz -h -C $SSHHOME $files | wc -c)
        if [ $SIZE -gt 65536 ]; then
            echo >&2 $'.sshrc.d and .sshrc files must be less than 64kb\ncurrent size: '$SIZE' bytes'
            exit 1
        fi
        ssh -t "$@" "
            if [ -e /etc/motd ];then cat /etc/motd; fi
            if [ \"\$(base64 --help | grep -e '-D')\" != \"\" ];then echo '-Di' > /tmp/b64decode; else echo '-di' > /tmp/b64decode; fi
            export SSHHOME=\$(mktemp -d -t .$(whoami).sshrc.XXXX)
            echo $'"$(cat `which sshrc` | base64)"' | base64 \$(cat /tmp/b64decode) > \$SSHHOME/sshrc
            chmod +x \$SSHHOME/sshrc
            echo $'"$( cat << 'EOF' | base64
#!/usr/bin/env bash
exec bash --rcfile <(echo '
if [ -e /etc/bash.bashrc ]; then source /etc/bash.bashrc; fi
if [ -e ~/.bashrc ]; then source ~/.bashrc; fi
export PATH=$PATH:'$SSHHOME'
source '$SSHHOME'/.sshrc;
')
EOF
)"' | base64 \$(cat /tmp/b64decode) > \$SSHHOME/bashsshrc
            chmod +x \$SSHHOME/bashsshrc
            export SSHRCCLEANUP=\$SSHHOME
            echo $'"$(tar cz -h -C $SSHHOME $files | base64)"' | base64 \$(cat /tmp/b64decode) | tar mxz -C \$SSHHOME
            export SSHHOME=\$SSHHOME
            bash --rcfile \$SSHHOME/bashsshrc
            "
    else
        echo "No such file: $SSHHOME/.sshrc"
    fi
}
if [ $1 ]; then
    sshrc $@
else
    ssh
fi
